=== sky-mxc/xmlDemoJava/student.dtd
<!ELEMENT students (student*) >
	<!ELEMENT student (name,college,telephone,notes) >
	<!ATTLIST student age CDATA "20">
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT college (#PCDATA)>
	<!ATTLIST college leader CDATA "leader">
	<!ELEMENT telephone (#PCDATA)>
	<!ELEMENT notes (#PCDATA)>

=== sky-mxc/xmlDemoJava/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sutdents SYSTEM "student.dtd">
<students>
	<student age="25">
		<name >张三</name>
		<college>PC学院</college>
		<telephone>627987234</telephone>
		<notes>男，1998年出生，硕士，现就读于北京邮电大学</notes>
	</student>
	<student >
		<name>李四</name>
		<college leader="leader3">历史系</college>
		<telephone>627987234</telephone>
		<notes>男，1998年出生，硕士，现就读于北京邮电大学</notes>
	</student>
</students>
